POST http://localhost:5000/api/properties
Content-Type: application/json

{
    "adresse": "Gelendzhik Urban Okrug, Krasnodar Krai, Russia", "proprietaire": "Vladimir Putin", "type": "Maison", 
    "nbPieces": "100", "superficie": "17691", "etat": "Neuf", "prix": "1400000000", "date": "2010-01-01 00:00", 
    "ville": "Gelendzhik", "nbGarages": "40", "image": "https://ichef.bbci.co.uk/news/976/cpsprodpb/1695D/production/_116590529_download.png"
}

###
PUT http://localhost:5000/api/properties/293
Content-Type: application/json

{
    "adresse": "742 Evergreen Terrace", "proprietaire": "Simpson family", "type": "Maison", 
    "nbPieces": 4, "superficie": "120 m2", "etat": "Bon etat", "prix": 101000, "date": "2050-05-05 05:05", 
    "ville": "Springfield", "nbGarages": "1", "image": "https://static.wikia.nocookie.net/simpsons/images/6/65/800px-742_Evergreen_Terrace.png/revision/latest?cb=20170101225756"
}

###
DELETE http://localhost:5000/api/properties/290

###
POST http://localhost:5000/authentication/adminLogin
Content-Type: application/json

{
    "Id_Admin": "super_admin", 
    "password": "$2dlwlsmqw6vRM9LGPZ6dskjd6Ha6lT6OnId0f1EUshSp8AoOImVeSECGRa3aFgu" 
}

###
POST http://localhost:5000/authentication/login
Content-Type: application/json

{
    "email": "abc@gmail.com", 
    "password": "123" 
}

###
POST http://localhost:5000/authentication/signup
Content-Type: application/json

{
    "email": "abc@gmail.com", 
    "password": "123" 
}

###
GET http://localhost:5000/authentication/logOK
{
  "user": "Registered_user",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjUzMzQwMDMxLCJleHAiOjE2NjExMTYwM
zF9.kEIYrZXzZBIpaTFvo4Y1urlYT-tFvIsEkpDcNDMMZBE",
  "cookies": { "expiresIn": 2022-08-21T21:07:11.810Z }
}

###
POST http://localhost:5000/authentication/forgotPassword
Content-Type: application/json

{
    "email": "abc@gmail.com"
}
